### ISSUE TITLE
Мелкие фиксы старницы товара

### ISSUE THREAD

**Issue by p-p-m** [p-p-m/ffw#24]
1) по этой ссылке:
   http://s020.radikal.ru/i705/1508/d1/c54e20e30d49.jpg
1. сделать ячейку побольше, так чтобы на неё можно было попасть
2. выделить другим тоном и рамкой количество

2) Ширина строки категории должна быть стандартной, с выравниванием по центру по вертикали. В стандартную ширину должны помещаться две строчки.
http://s020.radikal.ru/i723/1508/67/8858bf3c3b65.jpg

3) a) Кнопки «больше» «меньше» слишком маленькие;
    c) Должно быть выделение раздела, который просматривается
    http://s017.radikal.ru/i403/1508/57/c7659ff5da7e.jpg

4) курсор на номере телефона должен стоять на месте, куда будет вводиться цифра:
     http://s008.radikal.ru/i306/1508/c4/fc35562bc083.jpg
     но не так, как у нас сейчас:
     http://s017.radikal.ru/i406/1508/f0/1d2800405eea.jpg

5) сделать чтобы около характеристики был знак ? и показывалось описание характеристики если оно есть

**Comment by Damnfriend** [comment]
Если на баннере картинка с белым фоном, стрелок переключения между картинками не видно:
http://s011.radikal.ru/i315/1508/98/24a4e2592645.png

**Comment by mikeyakymenko** [comment]
Кнопки больше меньше – это сложно. Ибо это стандартный инпут.
Если критично то сделать то можно...

**Comment by Damnfriend** [comment]
По вашему мнению на эти кнопки вообще реально нажать? Может не стоить делать изначально неюзабельные вещи?

**Comment by mikeyakymenko** [comment]
Может стоит понимать о чем речь? Это стандартный input field для чисел. Изначально не было сказано что нужны +/- в этой таблице, я их и не сделал. Поэтому и уточнил, критично это или нет.

Тоже самое по 1-му пункту. Это стандартный чекбокс.

Не ясно по 5-му пункту. Знак вопроса, имеется ввиду иконка, и что при нажатии, или просто знак вопроса?

**Comment by mikeyakymenko** [comment]
Все решили с Пашей.

**Comment by p-p-m** [comment]
Просотрел то что сделано: немного странно подсвечиваются выбраные отделы. Например нажимаю на "Характеристики" а подсвечивается раздел "Выбор товаров". Такое ощущение что подсветка идет на один раздел выше чем надо.

**Comment by p-p-m** [comment]
Сюда же: Там комменты немного передалались - у нас нет имя пользователя и его значка, но есть позитивные и негативные стороны. Я сделал чтобы они показывались, но смотрятся они коряво. Доделай пожалуйста.

**Comment by mikeyakymenko** [comment]
Только если очень мало материала, тогда такое случается... хотя у меня такого нет. :( Нужно отловить.

**Comment by mikeyakymenko** [comment]
Update from sep 11

1 – done
2 – done
3 – done
4 – done

**Comment by mikeyakymenko** [comment]
@Damnfriend стрелки поправил, теперь и на белом фоне видно. :+1:

**Comment by mikeyakymenko** [comment]
5 – done.

**Comment by mikeyakymenko** [comment]
@Damnfriend уточните у @p-p-m когда это все дело на стейджинг сервере попадет.

**Comment by p-p-m** [comment]
Это все перепроверил. Вроди работает.
