### ISSUE TITLE
Фикс #1

### ISSUE THREAD

**Issue by Damnfriend** [p-p-m/ffw#25]
При сохранении существующей подкатегории появляется такая ошибка:
http://s020.radikal.ru/i709/1508/4f/85b0316cac37.jpg
Сохраненные характеристики товара не отображаются на странице товара:
http://s019.radikal.ru/i640/1508/26/b36f970d4290.jpg
При создании объекта в галереи:
http://s019.radikal.ru/i602/1508/d6/00182995b942.jpg

**Comment by p-p-m** [comment]
ошибки 1 и 3 связаны с картинками, я их уже чинил нно видимо слетело после обновления :/

2 - неправильный input

**Comment by p-p-m** [comment]
ошибки начали падать изза последнего апдейта. сейчас будут падать ошибки при добавлении картинки в любом месте
