### ISSUE TITLE
Фиксы/оценка

### ISSUE THREAD

**Issue by Damnfriend** [p-p-m/ffw#26]
1.  Возможность перемещения характеристик или возможность задавать им порядковый номер и соответственно изменение порядка их отображения на сайте
   http://s020.radikal.ru/i716/1508/a6/0693cec0d0aa.jpg
2.  Сделать какие-то «ячейки» для упрощения заполнения характеристик на странице товара (попадать курсором  на место между двумя точками и скобкой неудобно)
   http://s012.radikal.ru/i319/1508/93/09af2228e6da.jpg
3.  В  админке, в разделах Categories, Subcategories и  Products нужно разделить, например заходя в Products там сделать выбор категории из которой ты хочешь увидеть список товаров  (или выпадающие списки, все равно как) 
4.  У товаров разная высота ячеек,  нету дерева переходов и цена не полностью отображается в ячейке (да и сами ячейки не мешало бы как-то обрамить и сделать выравнивание по центру)
   http://s52.radikal.ru/i138/1508/cd/b5eb609115fd.jpg
5.  При обновлении страницы каталога все изображение «прыгает». Хорошо видно когда стоит отображение плиткой, после обновления страницы страница сначала загружается строками с галочкой возле иконки отображения строками и после этого возвращается к отображению плиткой

**Comment by p-p-m** [comment]
> Возможность перемещения характеристик или возможность задавать им порядковый номер и соответственно изменение порядка их отображения на сайте http://s020.radikal.ru/i716/1508/a6/0693cec0d0aa.jpg

я предлагаю сделать как с продуктами рейтинг - чем выше число тем выше характеристика будет показыватся, это поможет учитывать те категории, которые ты относятся не к заданой категории и секцмм

**Comment by Damnfriend** [comment]
Последнюю часть фразы не понял, но с рейтингом пойдет, как раз то что нужно

**Comment by p-p-m** [comment]
ок, по всему остальному понятно, буду отписывать как будет готово

**Comment by p-p-m** [comment]
пункты 4 и 5 перекинул сюда: https://github.com/p-p-m/ffw/issues/29

**Comment by p-p-m** [comment]
1, 3 - сделал
2 - тоже сделал, но максимально просто для меня. Если не подойдет то нужно будет обсудить как правильно.
