### ISSUE TITLE
Галерея и добавление товара

### ISSUE THREAD

**Issue by Damnfriend** [p-p-m/ffw#27]
1. При создании товара в новой подкатегории появилась обшибка, но товар сохранился на сайте (он есть и сейчас, название "Кран для накопительного бака бытовой системы обратного осмоса"). После нажатия на товар в разделе products появляется ошибка:
   http://s020.radikal.ru/i710/1508/90/d82cc328fbb6.jpg
2. После создания в галереи объекта без названия, его невозможно выбрать и зайти в него:
   http://s017.radikal.ru/i437/1508/28/3c7880b982e6.jpg

Сама страница галереи и просмотр картинок выглядит как непонятно что:
http://s013.radikal.ru/i325/1508/c5/ab5085d7ffd5.jpg
http://s017.radikal.ru/i444/1508/92/7ee4ff7bea54.jpg

**Comment by p-p-m** [comment]
Галерея не входит в список страниц этой части. Она в разработке и будет в 3тей фазе. Вот спеки по 2 фазе: https://docs.google.com/document/d/1JHOOvdUnuFJLvBR8wG0aWbi0fTGaP-d2hu0y5O0OPh0/edit Поэтому галерею можешь пока что совсем не смотреть.

**Comment by p-p-m** [comment]
Исправил формирование slug`a продукта(изза этого была ошибка)
