### ISSUE TITLE
Фиксы страницы со списком товаров

### ISSUE THREAD

**Issue by p-p-m** [p-p-m/ffw#29]
1. У товаров разная высота ячеек, нету дерева переходов и цена не полностью отображается в ячейке (да и сами ячейки не мешало бы как-то обрамить и сделать выравнивание по центру) http://s52.radikal.ru/i138/1508/cd/b5eb609115fd.jpg
2. При обновлении страницы каталога все изображение «прыгает». Хорошо видно когда стоит отображение плиткой, после обновления страницы страница сначала загружается строками с галочкой возле иконки отображения строками и после этого возвращается к отображению плиткой

**Comment by p-p-m** [comment]
данные для дерева перехода еще нет, отпишу как появятся.

**Comment by mikeyakymenko** [comment]
Появились, или пока не трогаем?

По пункту 2 сделай плиз, новое issue, нам нужно сделать preloader (ну типа кружочка такого который крутиться.)

**Comment by p-p-m** [comment]
> Появились, или пока не трогаем?

сделай пожалуйста статикой сам допишу переменные

**Comment by p-p-m** [comment]
> По пункту 2 сделай плиз, новое issue, нам нужно сделать preloader (ну типа кружочка такого который крутиться.)

не обязательно делать прелоадер - можешь просто поставить чтобы сразу грузился нужный шаблон в темплейте. Как тебе проще.

**Comment by p-p-m** [comment]
Дерева переходов я так и не вижу. Цифры в ячейки так и не помещаются. Тикет закрыть не могу.

**Comment by mikeyakymenko** [comment]
See PR [#46](https://github.com/p-p-m/ffw/pull/46).

**Comment by p-p-m** [comment]
works.
