### ISSUE TITLE
Доработки по фазе 2

### ISSUE THREAD

**Issue by p-p-m** [p-p-m/ffw#34]
1. Страница заказа. Содержит таблицу корзины и форму оформления заказа с именем заказчика, емейлом, телефоном, и другими контактами. В таблице корзины должен показыватся список покупок, количество, количество можно менять, также можно удалять товары из коризны.
2. Попап добавления коментария(отзыва): поля: преимущества, недостатки + кнопки добавить/отменить.
3. Меседж, типа "товар добавлен в корзину" или "отзыв отправлен на рассмотрение" и т.д.
4. Попап при покупке товара со страницы списка товаров. После нажатия на кнопку купить:
   - если у товара много модификаций то показывается попап в котором показывается список модификаций (как на странице просмотра этого товара) и внизу есть кнопки "купить" и "купить в один клик" с телефоном. Область со списком модификаций скролится. кнопки - нет. 
   - если у товара 1  модификация то просто показывается названия товара, его цена, количество, которое можно менять и тоже кнопки "купить" и "купить в один клик" (этого нет в спеках, все кроме остальное - есть)

**Comment by mikeyakymenko** [comment]
Сделано же, @p-p-m плиз, если сделано закрой ишью, если нет, пиши что да как.

**Comment by p-p-m** [comment]
я перепроверю, сорри еще не добрался. Мне просто нужно чтобы знать что смотреть

**Comment by p-p-m** [comment]
Остался пункт 4 для закрытия.

**Comment by mikeyakymenko** [comment]
Pull Feature/buy popup

**Comment by p-p-m** [comment]
Попап был сделан неправильно :/

Я примерно переделал как надо, но возможно будут нужны доделки. Этот тикет закрываю.
