### ISSUE TITLE
Загрузка каталога товаров

### ISSUE THREAD

**Issue by p-p-m** [p-p-m/ffw#41]
При обновлении страницы каталога все изображение «прыгает». Хорошо видно когда стоит отображение плиткой, после обновления страницы страница сначала загружается строками с галочкой возле иконки отображения строками и после этого возвращается к отображению плиткой

**Comment by mikeyakymenko** [comment]
Проверь, там стоит PR (https://github.com/p-p-m/ffw/pull/45)

**Comment by p-p-m** [comment]
Этот тикет сделан неправильно. Теперь оно прыгает в обратную сторону. Если поставить изображение списком и перезагрузить страницу, то сначала показывается плитка.

**Comment by p-p-m** [comment]
Переделал сам. Вроди работает.
