### ISSUE TITLE
Финальные доработки по второму этапу проекта. Часть 1

### ISSUE THREAD

**Issue by p-p-m** [p-p-m/ffw#47]
1. Число в корзине съехало. https://www.diigo.com/item/image/5bmcv/14cm
2. Окошко корзины не исчезает при нажатии на любую другую часть экрана, только если клацнуть опять на корзину.
3. Не рендарятся стили breadcrumps при загрузке страницы. Появляются попапы на страницах. Как по мне, то проще всего будет сделать preloader.
4. Добавить растояние между кнопками: https://www.diigo.com/item/image/5bmcv/m03c
5. Привести в порядок отображение цены в товаре с одной конфигурацией: https://www.diigo.com/item/image/5bmcv/n4kx
6. Хлебные крошки на странице списка товаров показываются ниже чем на всех остальных страницах: resource://jid0-gxjllfbcoax0lcltedfrekqdqpi-at-jetpack/as-ff/data/edit.html
7. Ссылки в хлебных крошках не должны быть в режиме CAPSLOCK.
8. Я убрал навигатор по странице корзины так как он там не нужен. Нужно отцентрировать страницу. https://www.diigo.com/item/image/5bmcv/o45y

**Comment by mikeyakymenko** [comment]
3й пункт вообще ничего не понял. :)

**Comment by mikeyakymenko** [comment]
See Pull request [#49](https://github.com/p-p-m/ffw/pull/49)

**Comment by p-p-m** [comment]
1 - ok
2 - ok
3 - ok
4 - ok
5 - я не уверен что это правильный вариант, но пока что оставляем.
6 - ок
7 - ок
8 - ок

Но пропал попап со страницы списка товаров

**Comment by p-p-m** [comment]
сейчас смотрю в чем проблема
