### ISSUE TITLE
Корзина

### ISSUE THREAD

**Issue by p-p-m** [p-p-m/ffw#51]
> 1. Хотя бы иконку какую-то
> 2. тображение нескольких добавленных товаров при нажатии на иконку корзины, сейчас это >при нажатии на цифру с кол-во добавленных товаров   (если их много, то последних). >Количество – на усмотрение дизайнера.
> 3. Возможность удалить товары из выпадающего списка 

Сейчас действительно смотрится там все коряво. 
1. Список: я его вырезал, так как он совсем криво смотрелся. Добавь его пожалуйста и посмотри чтобы нормально отображались товары с длинными именами. Была надпись "последние добавленые". Ну и жедательно чтобы крестики удаления были конзистентны с остальными частями сайта.
2. Инока: может так как-то переделать то что сейчас есть? Я лично вижу значек корзины и справа от него или снизу надпись "В корзине N товаров на сумму M гривен". Если в Корзине не 0 товаров то около икноки есть яркий кружек который показывает сколько товаров в корзине.

**Comment by mikeyakymenko** [comment]
А этот ишью разве не должен быть закрыт?

**Comment by p-p-m** [comment]
я тут так и не увидел пункта

> 1. Хотя бы иконку какую-то
