### ISSUE TITLE
Frontend-only issues. Part 1

### ISSUE THREAD

**Issue by p-p-m** [p-p-m/ffw#52]
1. > Номера телефонов, e-mail, дерево переходов  нужно сделать более жирным шрифтом, они не видны.
2. > Шрифт – сделать строгим, завитушки убрать  (вердана или аналогичный).
3. > Баннер – подсвечивать область перехода на следующий баннер или сделать иконки с картинкой следующего баннера (или еще как-то)
4. > Картинки товара не кликабельны (Вот товар с картинками, при нажатии ничего не происходит http://46.101.31.58/product/red-green-blue-filter/)
5. >  Высота ячейки по-прежнему может быть разной : http://c2n.me/3o4F5eT. Это касается как отображения «плиткой», так и отображения «строками». Также она зависит от наличия/отсутствия картинки товара. Может стоит сделать стандартную ячейку и если, к примеру, название не помещается то ставить три точки («…») или как-то так.
6. > В строке меню видимо есть «мертвые зоны», т.к. просто водя курсором по меню, оно закрывается. Видео: http://www.ex.ua/418160341274
7. > Внешний вид модификации товара – визуально разделить название и характеристики товара (разные ячейки или разные строки, другой шрифт и т.д.), т.к. так как сейчас http://c2n.me/3o5leg4 абсолютно не читабельно.
8. > Расстояние между названием и кратким описанием: http://c2n.me/3o6b3qK
9. > Краткое описание товара в режиме просмотра «Плиткой» сокращается до нескольких слов: http://c2n.me/3o6kejY

**Comment by mikeyakymenko** [comment]
8 – не понимаю вообще о чем речь :/

**Comment by mikeyakymenko** [comment]
9 – я спрашивал об этом сто раз, говорили так и нужно. Теперь расскажите как нужно, я сделаю.

**Comment by mikeyakymenko** [comment]
Паш, на 8, 9 будут новые бранчи, бранч [fixes/issue52](https://github.com/p-p-m/ffw/pull/54) можно принимать

**Comment by p-p-m** [comment]
8 - уже не актуально.

**Comment by p-p-m** [comment]
1 - done
2 - шрифт не поменян в верхнем меню. Но я вынесу это в дргуой тикет.
3 - Загружаю картинки с белыми краями и стрелки не видны. Не вижу что поменялось.
4 - Картинки на странице товара так и остались не кликабельными :/
5 - done (формально :) )
6 - done
7 - done
8 - closed

**Comment by p-p-m** [comment]
Итого осталось для закрытия:  3, 4, 9 

По 9 я вижу это так:

при показе продукта плиткой есть области:
1. **название продукта** - занимает максимум три строчки. Если название длинее - ставится три точки, как сейчас в описании, если короче - то центрируется по вертикали
2. **описание продукта** - занимает 4 строчки - если длинее - ставится три точки. Если короче - то центрируется по вертикали.
3. **картинка** - всегда одинакового размера, если картинки нет - то показывается пустое место, кнопка купить вверх при этом не двигается.
4. **цена** - всегда находится внизу над кнокой "купить"
5. **кнопка купить** - всегда назодится в самом низу.

Главное: оюласти всегда должны находится на одном уровне, кнопка купить одного товара не может находится справа от картинки другого товара.
